### ISSUE TITLE
Increase/decrease the contrast of background image to make the text more readable.

### ISSUE THREAD

**Issue by naved232doom** [pcon-hacktoberfest-21/Tap-Portal-Frontend#16]
Make the text more readable. You can refer to linear gradient in CSS. Attach screenshot before submitting PR.

![image](https://user-images.githubusercontent.com/65990919/137578886-ed83785c-d849-43ca-b1df-dab71028acdf.png)

**Comment by DilkiSasikala** [comment]
Hi, can you assign this to me?

**Comment by harshitasrivasatva** [comment]
Hey, I can do this, can you assign me
